# Generated by Django 5.1.1 on 2024-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time_of_reserve',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время брони'),
        ),
    ]
