# Generated by Django 5.1.1 on 2024-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_table_user_name_table_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='time_end_reserve',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца брони'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_of_reserve',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала брони'),
        ),
    ]
