# Generated by Django 5.1.1 on 2024-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_table_time_end_reserve_alter_table_time_of_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time_end_reserve',
            field=models.DateTimeField(blank=True, help_text='Введите дату в формате ГГГГ-ММ-ДД ЧЧ:ММ', null=True, verbose_name='Время конца брони'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_of_reserve',
            field=models.DateTimeField(blank=True, help_text='Введите дату в формате ГГГГ-ММ-ДД ЧЧ:ММ', null=True, verbose_name='Время начала брони'),
        ),
    ]
